version: '3.9'

services:
    postgresql:
        image: postgres:16
        container_name: pgdb
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
    rabbitmq:
        image: rabbitmq:3.13-management
        container_name: rabbitmq
        restart: always
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
        ports:
            - "11001:5672"
            - "11002:15672"
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq

volumes:
    postgres_data:
    rabbitmq_data: