name: CI

on:
  pull_request:
    branches: [ "dev" ]
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./src

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ./src
