name: Build Checks

on:
  pull_request:
    branches: [ "dev" ]
  push:
    branches: [ "master" ]

jobs:
  build_core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup dotnet 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: |
          dotnet restore ./src/eBar.Core/eBar.Core.csproj
          dotnet build ./src/eBar.DataStorage/eBar.DataStorage.csproj
          dotnet build ./src/eBar.MessageBroker/eBar.MessageBroker.csproj
          dotnet build ./src/eBar.Api/eBar.Api.csproj
          dotnet build ./src/eBar.UnitTests/eBar.UnitTests.csproj
      - name: Disable GitHub warning matching
        run: echo "::remove-matcher owner=csc::"
      - name: Build applications
        run: |
          dotnet build ./src/eBar.Core/eBar.Core.csproj --no-restore --configuration Release
          dotnet build ./src/eBar.DataStorage/eBar.DataStorage.csproj --no-restore --configuration Release
          dotnet build ./src/eBar.MessageBroker/eBar.MessageBroker.csproj --no-restore --configuration Release
          dotnet build ./src/eBar.Api/eBar.Api.csproj --no-restore --configuration Release
          dotnet build ./src/eBar.UnitTests/eBar.UnitTests.csproj --no-restore --configuration Release
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: core-build
          path: src/**/bin/Release
          
  build_framework:
    runs-on: windows-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
      - name: Restore dependencies
        run: nuget restore ./src/eBar.sln
      - name: Disable GitHub warning matching
        run: echo "::remove-matcher owner=csc::"
      - name: Build applications
        #run:
        run: echo "No windows apps sets. Skipped"

  test:
    runs-on: windows-latest
    needs: build_core
    steps:
#      - name: Checkout branch
#        uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: core-build
      - name: Setup dotnet 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore ./src/eBar.sln
      - name: Disable GitHub warning matching
        run: echo "::remove-matcher owner=csc::"
      - name: Create appsettings.json
        run: echo '${{ secrets.APPSETTINGS_JSON }}' > src/eBar.UnitTests/appsettings.json
      - name: Test dotnet projects
        run: dotnet test ./src/eBar.sln --no-restore --configuration Release --verbosity normal