name: Build Checks

on:
  pull_request:
    branches: [ "dev" ]
  push:
    branches: [ "master" ]

jobs:
# ------------- #
# Core projects #
# ------------- #
  build_core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Build dotnet projects
        run: |
          dotnet build src/eBar.Api/eBar.Api.csproj --configuration Release

  test_core:
    runs-on: ubuntu-latest
    needs: build_core
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Test dotnet projects
        run: |
          dotnet test src/eBar.UnitTests/eBar.UnitTests.csproj --no-build --verbosity normal

# ------------------ #
# Framework projects #
# ------------------ #
  build_framework:
    runs-on: windows-latest
    steps:
    - name: Setup MSBuild
      run: echo "no .Net Framework applications. Skipped"
      # - uses: actions/checkout@v3
      # - uses: microsoft/setup-msbuild@v2
      #   run: |
      #     msbuild src/eBar.Waiter/eBar.Waiter.csproj /p:Configuration=Release

  test_framework:
    runs-on: windows-latest
    needs: build_framework
    steps:
    - name: Setup MSBuild
      run: echo "no .Net Framework applications. Skipped"
      # - uses: actions/checkout@v3
      # - uses: microsoft/setup-msbuild@v2
      #   run: |
      #     vstest.console.exe src/eBar.WinUnitTests/bin/Release/*.dll
