name: Build Checks

on:
  pull_request:
    branches: [ "dev" ]
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup dotnet 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore ./src/eBar.sln
      - name: Build applications
        run: dotnet build ./src/eBar.sln --no-restore --configuration Release
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: core-build
          path: src/**/bin/Release

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Downloading artifacts from build
        uses: actions/download-artifact@v4
        with:
          name: core-build
          path: ./src
      - name: Setup dotnet 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Test dotnet projects
        run: dotnet test ./src/eBar.sln --no-build --no-restore --configuration Release --verbosity normal