name: Build Checks

on:
  pull_request:
    branches: [ "dev" ]
  push:
    branches: [ "master" ]

jobs:
  build_core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup dotnet 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        shell: bash
        run: |
          while IFS= read -r proj; do
            echo "Building $proj ..."
            dotnet restore "$proj"
          done < core.txt
      - name: Disable GitHub warning matching
        run: echo "::remove-matcher owner=csc::"
      - name: Build applications
        shell: bash
        run: |
          while IFS= read -r proj; do
            echo "Building $proj ..."
            dotnet build "$proj" --no-restore --configuration Release
          done < core.txt
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: core-build
          path: src/**/bin/Release
          
  build_framework:
    runs-on: windows-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
      - name: Restore dependencies
        run: nuget restore ./src/eBar.sln
      - name: Disable GitHub warning matching
        run: echo "::remove-matcher owner=csc::"
      - name: Build applications
        shell: pwsh
        run: |
          $projects = Get-Content ./build/framework.txt
          foreach ($proj in $projects) {
            Write-Host "Building $proj ..."
            msbuild $proj /p:Configuration=Release /p:TargetFrameworkVersion=v4.8 /m
          }

  test:
    runs-on: ubuntu-latest
    needs: build_core
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: core-build
      - name: Setup dotnet 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        shell: bash
        run: |
          while IFS= read -r proj; do
            echo "Building $proj ..."
            dotnet restore "$proj"
          done < core.txt
      - name: Disable GitHub warning matching
        run: echo "::remove-matcher owner=csc::"
      - name: Create appsettings.json
        run: echo '${{ secrets.APPSETTINGS_JSON }}' > src/eBar.UnitTests/appsettings.json
      - name: Test dotnet projects
        shell: bash
        run: |
          while IFS= read -r proj; do
            echo "Building $proj ..."
            dotnet test "$proj" --no-restore --configuration Release --verbosity normal
          done < tests.txt