name: CI

on:
  pull_request:
    branches: [ "dev" ]
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dummy build step
        run: echo "Build step skipped for empty repo"
      # - name: Setup .NET
      #   uses: actions/setup-dotnet@v3
      #   with:
      #     dotnet-version: '8.0.x'
      # - name: Restore dependencies
      #   run: dotnet restore
      # - name: Build
      #   run: dotnet build --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Dummy test step
        run: echo "Test step skipped for empty repo"
      # - name: Setup .NET
      #   uses: actions/setup-dotnet@v3
      #   with:
      #     dotnet-version: '8.0.x'
      # - name: Restore dependencies
      #   run: dotnet restore
      # - name: Test
      #   run: dotnet test --no-build --verbosity normal
